name: React to Fieldmate Release

on:
  repository_dispatch:
    types: [fieldmate-release]

jobs:
  on-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show release version
        run: |
          echo "Triggered by fieldmate release"
          echo "Version: ${{ github.event.client_payload.version }}"
