name: Mark stale issues and pull requests

on:
  schedule:
    # Every day at 00:00 UTC
    - cron: 0 0 * * *

jobs:
  stale:
    if: ${{ github.repository == 'digikwal/frappe_docker' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: >
            This issue has been automatically marked as stale. You have a week to explain why you believe this is an error.
          stale-pr-message: >
            This PR has been automatically marked as stale. You have a week to explain why you believe this is an error.
          stale-issue-label: no-issue-activity
          stale-pr-label: no-pr-activity
